channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  # - nodejs=16.14.2
  # - firefox=104.0

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - robotframework-browser==13.6.0
      # - robotframework-appiumlibrary==1.6.3
      - rpaframework==23.1.0 # https://rpaframework.org/releasenotes.html
      # - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/bd5/7c3c9ddf9973e/rpaframework-23.1.0-py3-none-any.whl#sha256=bd57c3c9ddf9973e844286fad32b1480a73ec3f1731fe8f657ef2b270f592a11
      - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/1e4/f0ff5c97f71ba/rpaframework_core-11.0.2-py3-none-any.whl#sha256=1e4f0ff5c97f71ba77f090c7fc621115b461fec9614bea7f0121496844a95ba3

# rccPostInstall:
#   - rfbrowser init
