channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  # - nodejs=16.14.2
  # - firefox=100.0

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - robotframework-browser==13.3.0
      # - robotframework-appiumlibrary==1.6.3
      # - rpaframework==16.0.0 # https://rpaframework.org/releasenotes.html
      - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/e36/393ce4a9c5f11/rpaframework_core-10.0.0-py3-none-any.whl#sha256=e36393ce4a9c5f11ed0c0131a94c890a739047052267bc20d9fccc6a88e0b17c
      - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/db4/8072221291653/rpaframework-16.0.0-py3-none-any.whl#sha256=db48072221291653055795f196b41b2b7070e308f5535915e5db095a31ed9c4a

# rccPostInstall:
#   - rfbrowser init
