channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - nodejs=17.9.0
  - firefox=100.0
  - geckodriver=0.30.0

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - robotframework-browser==12.4.0
      - rpaframework==14.1.0 # https://rpaframework.org/releasenotes.html

rccPostInstall:
  - rfbrowser init
