channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  # - nodejs=16.14.2
  # - firefox=104.0

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - robotframework-browser==13.6.0
      # - robotframework-appiumlibrary==1.6.3
      - rpaframework==19.2.0 # https://rpaframework.org/releasenotes.html
      # - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/8d3/55c52d3b08e77/rpaframework-16.0.0-py3-none-any.whl#sha256=8d355c52d3b08e770edd0de782bd86de6f42469eb7123fad9dbe68fb32492c59
      - selenium==4.4.0

# rccPostInstall:
#   - rfbrowser init
