channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  # - nodejs=14.15.4

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - robotframework-browser==12.0.0
      # - rpaframework==12.8.2 # https://rpaframework.org/releasenotes.html
      - https://github.com/mikahanninen/robots/blob/main/builds/rpaframework-12.8.2.40d67d72-py3-none-any.whl?raw=true

# rccPostInstall:
#   - rfbrowser init
