channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  # - nodejs=16.14.2
  # - firefox=104.0

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - robotframework-browser==13.6.0
      # - robotframework-appiumlibrary==1.6.3
      - rpaframework==22.2.1 # https://rpaframework.org/releasenotes.html

# rccPostInstall:
#   - rfbrowser init
