channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - nodejs=14.15.4

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - robotframework-browser==12.3.0
      - rpaframework==13.2.0 # https://rpaframework.org/releasenotes.html
      # - rpaframework-google==3.0.0

rccPostInstall:
  - rfbrowser init
