channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==15.1.1 # https://rpaframework.org/releasenotes.html
      # - rpaframework==14.1.1
      # - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/398/683ddc282c322/rpaframework-15.1.1-py3-none-any.whl#sha256=398683ddc282c3221e12c9c6c24dfdf2aac48a37d0e6934f34b3b35f07761701
