channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - rpaframework==15.1.0 # https://rpaframework.org/releasenotes.html
      # - rpaframework==14.1.1
      - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/0e2/29d434fee4299/rpaframework-15.1.0-py3-none-any.whl#sha256=0e229d434fee4299175f8d0f0d051c81b51af11cc514790aac1588933dac1286
