channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    # - rpaframework==12.8.1 # https://rpaframework.org/releasenotes.html
    - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/8b9/730383082aa85/rpaframework-12.8.1-py3-none-any.whl#sha256=8b9730383082aa85bc4895e27875e3e9c5c59e1ad837bddf02b4da578865ef95
