channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.5

  - pip=20.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==11.5.1  # https://rpaframework.org/releasenotes.html
    # - https://github.com/cmin764/robots/blob/main/work-items-api/builds/rpaframework-11.5.0.263.0842ed1-py3-none-any.whl?raw=true
