channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==12.8.0 # https://rpaframework.org/releasenotes.html
    - rpaframework-windows==2.1.0
    # - https://github.com/cmin764/robots/blob/main/builds/rpaframework_windows-2.1.0.53d345e-py3-none-any.whl?raw=true
