channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  - tesseract=5.1.0

  - pip=22.1.2
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework[cv]==15.1.4  # https://rpaframework.org/releasenotes.html
