channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    # - rpaframework==12.8.1  # https://rpaframework.org/releasenotes.html
    - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/13e/509a795db26ef/rpaframework-12.8.1-py3-none-any.whl#sha256=13e509a795db26ef7efd3c6ee4577174a21b52a69abb58df9ba191c2054dcdaa
    - rpaframework-windows==2.2.1
    # comtypes=1.1.11, pywin32==303, PRs: #278, #384
    # - https://github.com/cmin764/robots/blob/main/builds/rpaframework-12.8.1.ab9b6bb-py3-none-any.whl?raw=true
    # - https://github.com/cmin764/robots/blob/main/builds/rpaframework_windows-2.2.0.f1d4eb8-py3-none-any.whl?raw=true
