channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  - pip=22.1.2
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==15.1.3 # https://rpaframework.org/releasenotes.html
    # - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/f70/eda709d11f823/rpaframework-15.1.3-py3-none-any.whl#sha256=f70eda709d11f823f1fcd04ac46269dc0c1179ee97660adcec3fb339433947fe
