channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.9.13

  - pip=22.1.2
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    # - rpaframework==15.6.0 # https://rpaframework.org/releasenotes.html
    - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/51d/e0eff0f09d478/rpaframework_pdf-4.1.0-py3-none-any.whl#sha256=51de0eff0f09d4785bf2401cbef697d71fdd2c7d4f41d52a77bf7cd4060016a5
