channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.5

  - pip=21.3.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - --index-url https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/dev
    # - rpaframework==11.6.3  # https://rpaframework.org/releasenotes.html
    - https://github.com/cmin764/robots/blob/boost-plm/pdf-invoice-parse/builds/rpaframework-11.6.3.300-py3-none-any.whl?raw=true
    - https://github.com/cmin764/robots/blob/boost-plm/pdf-invoice-parse/builds/rpaframework_pdf-1.26.11.300-py3-none-any.whl?raw=true
