# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - truststore=0.8.0              # https://github.com/sethmlarson/truststore/blob/main/CHANGELOG.md
  - pip:
      - rpaframework==27.4.0      # https://rpaframework.org/releasenotes.html
      # - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/8d5/2556ec57b418d/java_access_bridge_wrapper-1.1.0-py3-none-any.whl#sha256=8d52556ec57b418dfbce319d7ed70160e7d21c5db9cff9606f73cf04cacb722f
      # - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/000/b495e895cd1d9/rpaframework-27.4.0-py3-none-any.whl#sha256=000b495e895cd1d9b178950980a0acdbe72b8ff5a797c603ffbeec4b55a30d00
