# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  # - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.6.1        # https://rpaframework.org/releasenotes.html
    # - rpaframework-28.6.0-py3-none-any.whl  # testing local wheels
    - robocorp==2.1.0             # https://pypi.org/project/robocorp
    - robocorp-truststore==0.9.1  # should be deployed in conda-forge as well
    # - https://github.com/cmin764/robots/raw/main/builds/robocorp_vault-1.3.6-py3-none-any.whl  # deploy latest `robocorp-vault` in `robocorp` post-merge
